version: '3.7'
services:
  app:
    image: k10/app:1.0.0
    networks:
      - public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend.loadbalancer.sticky=false"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.docker.network=public"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:k10.luongit.com"
        - "traefik.frontend.redirect.regex=^https?://www.k10.luongit.com/(.*)"
        - "traefik.frontend.redirect.replacement=https://k10.luongit.com/$${1}"
        - "traefik.redirectorservice.frontend.entryPoints=http"
        - "traefik.redirectorservice.frontend.redirect.entryPoint=https"
        - "traefik.webservice.frontend.entryPoints=https"
        - "traefik.port=3000"
networks:
  public:
    external: true